version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2024.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: build feed
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t udagram-api-feed $DOCKERHUB_USERNAME/udagram-api-feed:$TAG

      - run:
          name: build user
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t udagram-api-user $DOCKERHUB_USERNAME/udagram-api-user:$TAG

      - run:
          name: build reverseproxy
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t udagram-reverseproxy $DOCKERHUB_USERNAME/udagram-reverseproxy:$TAG

      - run:
          name: build frontend
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t udagram-frontend $DOCKERHUB_USERNAME/udagram-frontend:$TAG    

      - run:
          name: push docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:$TAG
            docker push $DOCKERHUB_USERNAME/udagram-api-user:$TAG
            docker push $DOCKERHUB_USERNAME/udagram-reverseproxy:$TAG
            docker push $DOCKERHUB_USERNAME/udagram-frontend:$TAG
