version: 2.1

jobs:
  build_and_push_images:
    working_directory: ~/app
    docker:
      - image: cimg/base:2024.12
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Images
          command: docker-compose -f docker-compose-build.yaml build --parallel

      - run:
          name: Tag Docker Images
          command: |
            docker tag reverseproxy:latest $DOCKERHUB_USERNAME/udagram-reverseproxy:${CIRCLE_BUILD_NUM} 
            docker tag udagram-api-user:latest $DOCKERHUB_USERNAME/udagram-api-user:${CIRCLE_BUILD_NUM}
            docker tag udagram-api-feed:latest $DOCKERHUB_USERNAME/udagram-api-feed:${CIRCLE_BUILD_NUM}
            docker tag udagram-frontend:local $DOCKERHUB_USERNAME/udagram-frontend:${CIRCLE_BUILD_NUM}

      - run:
          name: Push Docker Images
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:${CIRCLE_BUILD_NUM} 
            docker push $DOCKERHUB_USERNAME/udagram-api-user:${CIRCLE_BUILD_NUM} 
            docker push $DOCKERHUB_USERNAME/udagram-reverseproxy:${CIRCLE_BUILD_NUM} 
            docker push $DOCKERHUB_USERNAME/udagram-frontend:${CIRCLE_BUILD_NUM}

workflows: 
  version: 2 
  build_and_deploy: 
    jobs: 
      - build_and_push_images
