apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-api-feed